Repository amsalgultom/jasa-foto, pull requests merged in 2023-06, with the labels that each got.

#7 fix pages authentification login
  app/Http/Controllers/Auth/LoginRegisterController.php
  resources/views/layout-users/header.blade.php
Labels: bug, enhancement

#10 fix navbar
  resources/views/layout-users/header.blade.php
Labels: bug

#12 Update modul produk,model and callback midtrans
  app/Http/Controllers/OrderController.php
  app/Http/Controllers/ProductController.php
  app/Models/Product.php
  database/migrations/2023_06_20_061209_alter_table_models.php
  database/migrations/2023_06_20_061634_alter_table_products.php
  database/migrations/2023_06_20_062801_remove_column_from_models.php
  resources/views/models/index.blade.php
  resources/views/products/create.blade.php
  resources/views/products/index.blade.php
  routes/api.php
Labels: bug, enhancement

#13 Add new attrbute size on model
  app/Http/Controllers/PhotoModelController.php
  app/Models/PhotoModel.php
  public/uploads-images/models/1687342438-ERPdsa.png
  public/uploads-images/models/1687342484-ERPdsa.png
  public/uploads-images/models/1687342514-fds.png
  resources/views/models/create.blade.php
Labels: enhancement

#14 remove form harga on model
  resources/views/models/create.blade.php
  resources/views/models/edit.blade.php
Labels: bug

#15 RedirecOrder
  app/Http/Controllers/OrderController.php
  resources/views/pages/orderservice.blade.php
Labels: bug

#16 view produk model in order
  app/Http/Controllers/HomeController.php
  app/Models/Product.php
  resources/views/pages/orderservice.blade.php
Labels: bug

#20 report
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/PDFController.php
  composer.json
  composer.lock
  public/css/all.css
  public/css/sb-admin-2.css
  public/css/style-mobile.css
  public/css/style.css
  public/img/logo-min.png
  public/img/procedure/cek-jadwal.png
  public/img/procedure/fix-order.png
  public/img/procedure/hasil-photo.png
  public/img/procedure/pengiriman-produk.png
  public/img/procedure/sesi-photoshoot.png
  public/img/procedure/transaksi.png
  public/js/all.js
  resources/views/admin/document.blade.php
  resources/views/admin/report.blade.php
  resources/views/layout-users/header.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/sidebar.blade.php
  resources/views/pages/orderservice.blade.php
  resources/views/pages/ourservices.blade.php
  resources/views/pages/procedure.blade.php
  routes/web.php
Labels: enhancement

#23 Dev hayyu
  public/css/sb-admin-2.css
  resources/views/admin/client.blade.php
  resources/views/admin/listorders.blade.php
  resources/views/admin/report.blade.php
  resources/views/pages/orderservice.blade.php
Labels: enhancement

#26 Update order and my orders client
  app/Http/Controllers/Auth/LoginRegisterController.php
  resources/views/admin/report.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/layout-users/app.blade.php
  resources/views/layout-users/header.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/header.blade.php
  resources/views/layouts/sidebar.blade.php
  resources/views/models/index.blade.php
  resources/views/pages/detailorderservice.blade.php
  resources/views/pages/orderservice.blade copy.php
  resources/views/pages/orderservice.blade.php
  resources/views/products/index.blade.php
Labels: bug, enhancement

#28 add required check confirm prosedur before payment
  resources/views/home.blade.php
  resources/views/layout-users/footer.blade.php
  resources/views/pages/home.blade.php
  resources/views/pages/paymentorderservice.blade.php
  resources/views/welcome.blade.php
Labels: bug, enhancement

#30 redirect payment and format date model
  resources/views/pages/orderservice.blade.php
  resources/views/pages/paymentorderservice.blade.php
Labels: bug, enhancement

#32 List data set Desc and fix update produk and model
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/Auth/LoginRegisterController.php
  app/Http/Controllers/CustomerController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/OrderController copy.php
  app/Http/Controllers/OrderController.php
  app/Http/Controllers/PhotoModelController.php
  app/Http/Controllers/ProductController.php
  resources/views/client/detailorder.blade.php
  resources/views/models/create.blade.php
  resources/views/models/edit.blade.php
  resources/views/models/index.blade.php
  resources/views/products/create.blade.php
  resources/views/products/edit.blade.php
Labels: bug
